### PR TITLE
Renaming this variable 'font' to 'fontfamily' 

### PR DESCRIPTION
**Pull request by gnovos**
This fixes the issues with broken 'font-size'.

### CODE REVIEW

**Comment by maynarddemmon** [comment]
I figured out the source of the problem. There is an attribute named 'font' on text.dre. In CSS this attributes sets ALL the font properties at once. We use it just to set the font-family. The normal attribute handling causes a call to setStyle('font', value) which clobbers and previous font properties that were set. One way to fix this is to add 'font' to the hiddenAttributes map in layout.coffee (line 1415) so that setStyle will never get called for font.

**Comment by maynarddemmon** [comment]
So in conclusion, I think you should do the following:

1) Add the fontsize and fontfamily entry to stylemap.
2) Change the default of fontsize to 14.
3) Change font to fontfamily
4) Remove the setters for fontsize and fontfamily
5) Make sure tests work.

Sorry to micromanage your PR, but I can't resist detective work when something isn't behaving as expected.

**Comment by gnovos** [comment]
Oh man, of course!  Thanks, now this all makes sense.

**Comment by maynarddemmon** [comment]
looks good to me

**Pull request merged**
